OAUTH_TOKEN = 'YOUR OAUTH TOKEN'
username = 'BOT NAME'
channels = ['Channel List']
prefix = '<' #Desired Prefix.
bot_owner = "Bot Owner" # For private commands.
initial_msg = "Bot has joined. 🤖"
db_uri = "Your MongoDB URI"
user_access_token = "Your user access token"
client_id = "Your client ID"
githubToken = "Your Github Token"
GOOGLE_API_KEY = "Your Google API Key"
GROQ_API_KEY = "Your Groq API Key"
GENIUS_PROXY = "Your example proxy URL"